[package]
name = "rust_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.29.0"
csv = "1.0"
log = "0.4"
simplelog = "0.6"
env_logger = "0.10.0"